# Uncomment the next line to define a global platform for your project

platform :ios, '8.0'

target 'YYWeibo' do
    
    use_frameworks!
    
    pod 'SVProgressHUD', '1.1.3'
    pod 'AFNetworking'
end
